#define _POSIX_C_SOURCE 200809L
/* Hand-written lexer/parser/interpreter/main for Jester. */
#include "RRC.c"
#include <time.h>
static char *eval(Runtime*,char*,JType*);
static int balanced(const char*s,char o,char c){int d=0,q=0,b=0;for(;*s;s++){if(*s=='`'&&!q)b=!b;else if(*s=='"'&&!b)q=!q;else if(!q&&!b){if(*s==o)d++;if(*s==c&&!--d)return 1;}}return 0;}
static char *unquote(char*s){size_t n=strlen(s);if(n>=2&&((s[0]=='"'&&s[n-1]=='"')||(s[0]=='`'&&s[n-1]=='`'))){s[n-1]=0;return j_dup(s+1);}return NULL;}
static char *number_op(char *a,char op,char*b){double x=strtod(a,NULL),y=strtod(b,NULL),z=0;if(op=='+')z=x+y;if(op=='-')z=x-y;if(op=='*')z=x*y;if(op=='/')z=y?x/y:0;char out[64];snprintf(out,sizeof out,"%.15g",z);return j_dup(out);}
static char *call(Runtime*r,char*s,JType*t){char *open=strchr(s,'(');char *close=strrchr(s,')');if(!open||!close||close<open){*t=J_STRING;return j_dup("");}*open=0;char *path=j_trim(s),*inside=open+1;*close=0;const char *names[64],*vals[64];char *owned[128];size_t n=0,on=0;int q=0,b=0;char *start=inside;for(char*p=inside;;p++){if(*p=='`'&&!q)b=!b;else if(*p=='"'&&!b)q=!q;if((*p==','&&!q&&!b)||!*p){char save=*p;*p=0;char *part=j_trim(start),*eq=NULL; int pd=0; for(char *ep=part;*ep;ep++){if(*ep=='(')pd++; else if(*ep==')')pd--; else if(*ep=='='&&!pd){eq=ep;break;}} if(eq&&eq[1]!='='){*eq=0;names[n]=j_dup(j_trim(part));owned[on++]=(char*)names[n];part=j_trim(eq+1);}else names[n]="";JType z;vals[n]=eval(r,part,&z);owned[on++]=(char*)vals[n++];if(!save)break;start=p+1;}}
JesterBuiltin fn=jester_registry_find(&r->registry,path); JVar *method=rt_var(r,path); char *out=fn?fn(path,names,vals,n,r):(method?j_dup(method->value):j_dup(""));for(size_t i=0;i<on;i++)free(owned[i]);*t=J_STRING;return out;}
static char *eval(Runtime*r,char*s,JType*t){s=j_trim(s);char *u=unquote(s);if(u){*t=J_STRING;return u;}if(s[0]=='['&&s[strlen(s)-1]==']'&&balanced(s,'[',']')){*t=J_BLOCK;return j_dup(s);}if(strchr(s,'(')&&s[strlen(s)-1]==')')return call(r,s,t);if(!strcmp(s,"true")||!strcmp(s,"false")){*t=J_BOOL;return j_dup(s);}for(char*p=s+1;*p;p++)if(strchr("+-*/",*p)){char op=*p;*p=0;JType x,y;char*a=eval(r,s,&x),*b=eval(r,p+1,&y),*o=number_op(a,op,b);free(a);free(b);*t=J_STRING;return o;}JVar*v=rt_var(r,s);if(v){*t=v->type;return j_dup(v->value);}*t=J_STRING;fprintf(stderr,"Jester variable error: %s\n",s);return j_dup("");}
static int truth(Runtime*r,char *s){char *p=strstr(s," ≠ ");int ne=p!=NULL;if(!p)p=strstr(s," = ");if(!p){JType t;char*v=eval(r,s,&t);int x=strcmp(v,"false")&&strcmp(v,"");free(v);return x;}*p=0;char *rhs=p+(ne?4:3);JType a,b;char*x=eval(r,s,&a),*y=eval(r,rhs,&b);int z=!strcmp(x,y);free(x);free(y);return ne?!z:z;}
static void run(Runtime*r,char *src);
static void execute_value(Runtime*r,JVar*v){if(v->type==J_BLOCK){char*x=j_dup(v->value+1);x[strlen(x)-1]=0;run(r,x);free(x);}else if(v->type==J_FUNCTION){char*x=j_dup(v->value);JType t;char*z=eval(r,x,&t);free(z);free(x);}}
static void use_module(Runtime*r,char *line){char mod[256],lib[256];if(sscanf(line,"use %255s from %255s",mod,lib)!=2){fprintf(stderr,"Jester use error\n");return;}char path[4096];const char*home=getenv("HOME");snprintf(path,sizeof path,"%s/.jesterlibs/%s/modules/%s.jr",home?home:"",lib,mod);FILE*f=fopen(path,"rb");if(!f){snprintf(path,sizeof path,".jesterlibs/%s/modules/%s.jr",lib,mod);f=fopen(path,"rb");if(!f){snprintf(path,sizeof path,".jesterlibs_template/%s/modules/%s.jr",lib,mod);f=fopen(path,"rb");}}if(!f){fprintf(stderr,"Jester module error: %s\n",mod);return;}char buf[8192]={0};fread(buf,1,sizeof buf-1,f);fclose(f);run(r,buf);JVar*v=rt_var(r,mod);if(v){char alias[600];snprintf(alias,sizeof alias,"%s.%s",lib,mod);rt_set(r,alias,v->value,v->type);}}
static char *top_assign(char *s){int depth=0,q=0,b=0;for(char*p=s;p[0];p++){if(*p=='`'&&!q)b=!b;else if(*p=='"'&&!b)q=!q;else if(!q&&!b){if(*p=='[')depth++;else if(*p==']')depth--;else if(!depth&&p[0]=='='&&p[1]=='=')return p;}}return NULL;}
static void statement(Runtime*r,char *line){line=j_trim(line);if(!*line)return;if(!strncmp(line,"use ",4)){use_module(r,line);return;}size_t n=strlen(line);if(n>2&&line[n-1]==')'&&!strchr(line,' ')){char name[512];memcpy(name,line,n-2);name[n-2]=0;JVar*v=rt_var(r,name);if(v)execute_value(r,v);else {JType t;char*x=eval(r,line,&t);free(x);}return;}char *as=top_assign(line);if(as){*as=0;char *left=j_trim(line),*right=j_trim(as+2);JType t;char*v;if(left[0]=='['){v=eval(r,left,&t);rt_set(r,right,v,t);}else if(strchr(left,'(')){rt_set(r,right,left,J_FUNCTION);v=j_dup(left);}else{v=eval(r,right,&t);rt_set(r,left,v,t);}free(v);return;}JType t;char*v=eval(r,line,&t);free(v);}
static void run(Runtime*r,char *src){
 char *copy=j_dup(src),*save=NULL,*line=strtok_r(copy,"\n",&save);
 while(line){ char *comment=strstr(line,"##"); if(comment)*comment=0; line=j_trim(line);
  if(!strcmp(line,"[")){ char block[8192]="["; char *next; while((next=strtok_r(NULL,"\n",&save))){ strncat(block,"\n",sizeof block-strlen(block)-1); strncat(block,next,sizeof block-strlen(block)-1); if(j_trim(next)[0]==']')break; } line=block; statement(r,line); line=strtok_r(NULL,"\n",&save); continue; }
  if(!strcmp(line,"if")){char*cond=strtok_r(NULL,"\n",&save),*then=strtok_r(NULL,"\n",&save),*yes=strtok_r(NULL,"\n",&save),*els=strtok_r(NULL,"\n",&save),*no=strtok_r(NULL,"\n",&save);if(cond&&then&&yes&&els&&!strcmp(j_trim(then),"then")&&!strcmp(j_trim(els),"else"))statement(r,truth(r,j_trim(cond))?yes:no);line=strtok_r(NULL,"\n",&save);continue;} statement(r,line);line=strtok_r(NULL,"\n",&save); }
 free(copy);
}
int main(int argc,char**argv){if(argc!=2){fprintf(stderr,"usage: jester script.jr\n");return 64;}FILE*f=fopen(argv[1],"rb");if(!f){perror(argv[1]);return 66;}fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);char*s=calloc(1,n+1);fread(s,1,n,f);fclose(f);Runtime r={0};const char*bd=getenv("JESTER_BUILTINS");rt_load_builtins(&r,bd?bd:"builtins");run(&r,s);rt_free(&r);free(s);return 0;}
